name: Build & Deploy to PyPI

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'This workflow publishes to TestPyPI only. For production, create a GitHub Release.'
        required: false
        default: ""

  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v4

      - name: Install uv 💜
        uses: astral-sh/setup-uv@v6

      - name: Install and run ruff 🐶
        uses: astral-sh/ruff-action@v3

      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies 📦
        run: |
          uv sync --all-groups --frozen

      - name: Lint with flake8 ❄️
        run: |
          uv run flake8

      - name: Test with pytest ✅
        run: |
          uv run pytest tests

      - name: Version replacement based on tag ↔️
        if: github.ref_type == 'tag'
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "Tag version: $TAG_VERSION"
          uv version $TAG_VERSION

      - name: Build package 📦
        run: |
          uv build

      - name: Publish to TestPyPI 🧪
        if: github.event_name == 'workflow_dispatch'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN_TEST_PYPI }}
        run: |
          uv publish --index testpypi

      - name: Publish to PyPI 🚀
        if: github.event_name == 'release'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
        run: |
          uv publish
